# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://fauzihermawan.com"
title: Fauzi Ramadhan Hermawan  
copyright: "© [Fauzi Ramadhan Hermawan](https://fauzihermawan.com)"
theme: 
  - PaperMod
  - hugo-shortcode-gallery

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
#mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  # minifyOutput: true

pagination:
  disableAliases: true
  pagerSize: 10


menu:
  main:
  - name: Home
    url: 
    weight: 10
  - name: Portofolio
    url: portofolio/
    weight: 20       
  - name: Blog
    url: blog/
    weight: 30    
  - name: Tags
    url: tags/
    weight: 40          
  - name: Archive
    url: archives
    weight: 50
  - name: Search
    url: search/
    weight: 60


outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Fauzi Ramadhan Hermawan
  description: "I'm Fauzi Ramadhan Hermawan, a passionate 3D Artist specializing in game-ready assets 🎮✨ From modeling, rigging, texturing, and animation, I bring digital worlds to life with immersive characters, environments, and creatures."
  keywords: [Blog, Portfolio, 3D]
  author: Me
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  # displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowAllPagesInArchive: true
  ShowPageNums: true
  #ShowToc: true
  #TocOpen: true


  comments: true
  images: ["images/papermod-cover.png"]

  profileMode: 
    enabled: true
    title: "👋 Hey there!"
    subtitle: I'm **Fauzi Ramadhan Hermawan**, a passionate **3D Artist** specializing in **game-ready assets** 🎮✨ From **modeling, rigging, texturing, and animation**, I bring digital worlds to life with immersive **characters, environments, and creatures**.
    imageUrl: "home/pp.jpg"
    imageWidth: 210
    imageHeight: 210
    imageTitle: my image
    buttons: 
      - name: Resume
        url: "https://drive.google.com/file/d/1t4lYW5boVweNsmfUVjtxsfNwcwGbWzFe/view?usp=sharing"
      - name: Showreel
        url: "https://youtu.be/2AhnoveKi0s"
      - name: Artstation
        url: "https://www.artstation.com/fauzihermawan"

  socialIcons: 
    - name: email
      url: "mailto:mail@fauzihermawan.com"

    - name: linkedin
      url: "https://www.linkedin.com/in/fauzi-ramadhan-hermawan-71b600256/"

    - name: instagram
      url: "https://www.instagram.com/fzi_rh/"

    - name: youtube
      url: "https://www.youtube.com/@pawz3d"
      
    - name: behance
      url: "https://www.behance.net/fauzirh"

    - name: whatsapp
      url: "https://wa.me/6289649641520"

    - name: discord
      url: "https://discordapp.com/users/816812619679793204"


  #homeInfoParams:
  #  Title: "PaperMod's Demo"
  #  Content: >
  #    👋 Welcome to demo page of Hugo's theme PaperMod!

   #   - **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.

  #    - Feel free to show your support by giving us a star 🌟 on GitHub and sharing with your friends and social media .

 #     - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper/tree/4330c8b12aa48bfdecbcad6ad66145f679a430b3).


  label: 
    text: "FRH"
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
    favicon: "/favicon.png"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true

services:
  disqus:
    shortname: fauzi-ramadhan-hermawan